name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.2.0
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@v1.14.2
